name: Black

on:
  workflow_call:
    inputs:
      isort:
        required: false
        default: true
        type: boolean

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black isort

      - name: Lint with isort
        if: ${{ inputs.isort }}
        run: |
          isort --profile black --check --diff .

      - name: Lint with black
        run: |
          black --check --diff .

  isort:
    runs-on: ubuntu-latest
    if: ${{ inputs.isort }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install isort

      - name: Lint with isort
        run: |
          isort --profile black --check --diff .
