name: Prettier

on: [workflow_call]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Prettier
        run: npm install --global prettier

      - name: Lint
        run: prettier --check .
