name: Python Lint

on:
  workflow_call:
    inputs:
      black:
        required: false
        default: true
        type: boolean
      isort:
        required: false
        default: true
        type: boolean
      flake8:
        required: false
        default: true
        type: boolean

jobs:
  black:
    if: ${{ inputs.black }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install black isort

      - name: Lint with isort
        if: ${{ inputs.isort }}
        run: |
          isort --profile black --check --diff .

      - name: Lint with black
        run: |
          black --check --diff .

  flake8:
    if: ${{ inputs.flake8 }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install flake8

      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics
