name: Workflow Lint

on:
  push:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Install Prettier
        run: npm install --global prettier

      - name: Install shfmt
        run: |
          wget -O shfmt https://github.com/mvdan/sh/releases/download/v3.5.1/shfmt_v3.5.1_linux_amd64
          chmod +x shfmt

      - name: Install ShellCheck
        run: sudo apt-get install shellcheck

      - name: Lint with prettier
        run: prettier --check ".github/workflows/*.yml"

      - name: Dump workflow commands to scripts
        id: dump_workflow_scripts
        shell: python
        run: |
          import os
          import shutil
          import sys

          import yaml

          # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
          SHEBANGS = {
              "null": "#!/bin/bash -e",
              "bash": "#!/bin/bash -eo pipefail",
              "sh": "#!/bin/sh -e",
              "python": "#!/usr/bin/env python",
          }

          EXTENSIONS = {
              "null": "bash",
              "bash": "bash",
              "sh": "sh",
              "python": "py",
          }


          input_path = sys.argv[1]
          output_path = sys.argv[2]

          shutil.rmtree(output_path, ignore_errors=True)

          output = open(os.environ["GITHUB_OUTPUT"], "w")

          output.write("files<<EOF\n")

          for workflow_filename in os.listdir(input_path):
              if not workflow_filename.endswith(".yml"):
                  continue

              workflow_id = os.path.basename(workflow_filename).replace(".yml", "")

              with open(f"{input_path}/{workflow_filename}", "r") as f:
                  workflow = yaml.safe_load(f)

              if not workflow:
                  continue

              for job_id, job in workflow.get("jobs", []).items():
                  job_dirname = f"{output_path}/{workflow_id}/{job_id}"
                  os.makedirs(job_dirname, exist_ok=True)

                  for idx, step in enumerate(job.get("steps", [])):
                      if "run" not in step:
                          continue

                      shell = step.get("shell", "null")
                      if shell not in SHEBANGS:
                          continue

                      shebang = SHEBANGS[shell]
                      extension = EXTENSIONS[shell]
                      step_id = step.get("id", f"__run_{idx}")
                      name = step.get("name")
                      script = step.get("run")

                      filename = f"{job_dirname}/{step_id}.{extension}"

                      output.write(filename + "\n")
                      with open(filename, "w") as f:
                          f.write(f"{shebang}\n")
                          if name:
                              f.write(f"# name: {name}\n")
                          f.write("\n")
                          f.write(script)
                          if not script.endswith("\n"):
                              f.write("\n")

          output.write("EOF\n")

      - name: Lint with shfmt
        run: |
          read -a args <<< "$FILES"
          ./shfmt --diff "${args[@]}"
        env:
          FILES: ${{ steps.dump_workflow_scripts.outputs.files }}

      - name: Lint with ShellCheck
        run: |
          read -a args <<< "$FILES"
          shellcheck "${args[@]}"
        env:
          FILES: ${{ steps.dump_workflow_scripts.outputs.files }}
